USE `deisi_backend`;

INSERT INTO deisi_backend.company (id,description,img_src,name) VALUES
	 (83,'Descrição Accenture','https://ik.imagekit.io/smm2b6sqe/accenture_png_ezIy1Y3G4.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699625','Accenture'),
	 (84,'Descrição Microsoft','https://ik.imagekit.io/smm2b6sqe/microsoft_png_X7UzenKuNk.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792700103','Microsoft'),
	 (92,'Descrição CGI','https://ik.imagekit.io/smm2b6sqe/cgi_png_FMHGHQMKC.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699624','CGI'),
	 (91,'Descrição Everis','https://ik.imagekit.io/smm2b6sqe/everis_png_OpjT8ltCU.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699700','Everis'),
	 (90,'Descrição Link','https://ik.imagekit.io/smm2b6sqe/ling_png_qWU2lkere.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699838','Link'),
	 (88,'Descrição Novabase','https://ik.imagekit.io/smm2b6sqe/novabase_png_IFs-bx7pVS.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792700184','Novabase'),
	 (89,'Descrição Deloitte','https://ik.imagekit.io/smm2b6sqe/deloitte_png_aCDqTywIx.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699660','Deloitte'),
	 (93,'Descrição BOLD','https://ik.imagekit.io/smm2b6sqe/bold_png_2TsozlnvOu.png?ik-sdk-version=javascript-1.4.3&updatedAt=1650792699640','BOLD');

INSERT INTO deisi_backend.course (id,course_description,`degree`,title,url) VALUES
 	 (76,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.','Licenciatura','Engenharia Informática','https://www.ulusofona.pt/licenciaturas/engenharia-informatica'),
 	 (77,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Est ullamcorper eget nulla facilisi.','Licenciatura','Informática Gestão','https://www.ulusofona.pt/licenciatura/informatica-de-gestao'),
 	 (78,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.','Licenciatura','Informática Redes e Telecomunicações','https://www.ulusofona.pt/licenciatura/engenharia-informatica-redes-e-telecomunicacoes'),
 	 (79,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Est ullamcorper eget nulla facilisi.','Mestrado','Data Science','https://www.ulusofona.pt/mestrados/ciencia-de-dados'),
 	 (80,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. ','Mestrado','Engenharia Informática e Sistemas Informação','https://www.ulusofona.pt/mestrados/engenharia-informatica-e-sistemas-de-informacao'),
 	 (81,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.','Doutoramento','Novos Media e Sistemas Ubíquos','https://www.ulusofona.pt/doutoramentos/informatica-novos-media-e-sistemas-ubiquos');

INSERT INTO deisi_backend.page (id,page_name,page_text,stat,stat_text,title) VALUES
	 (103,'Metrics','Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur non eos id neque amet. Vero quaerat soluta ratione facere maxime, odio nemo magnam perspiciatis sunt eum atque! Earum adipisci suscipit asperiores, placeat qui cumque. Nostrum corrupti veritatis at veniam id odio, nisi incidunt nobis vitae laudantium laboriosam officiis saepe dolores architecto nesciunt tempore nihil, quos voluptates tenetur cumque natus voluptatum? Dicta vitae repellendus cupiditate eum iste earum velit ex cum','500+','alunos formados em 2008. Mais de 140 inscrições em 2020.','O teu lugar é aqui'),
	 (107,'Companies','Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur non eos id neque amet. Vero quaerat soluta ratione facere maxime, odio nemo magnam perspiciatis sunt eum atque! Earum adipisci suscipit asperiores, placeat qui cumque. Nostrum corrupti veritatis at veniam id odio, nisi incidunt nobis vitae laudantium laboriosam officiis saepe dolores architecto nesciunt tempore nihil, quos voluptates tenetur cumque natus voluptatum? Dicta vitae repellendus cupiditate eu','98.7%','de empregabilidade. 1000€ de salário médio inicial.','O mercado espera-te!'),
	 (105,'Students','Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur non eos id neque amet. Vero quaerat soluta ratione facere maxime, odio nemo magnam perspiciatis sunt eum atque! Earum adipisci suscipit asperiores, placeat qui cumque. Nostrum corrupti veritatis at veniam id odio, nisi incidunt nobis vitae laudantium laboriosam officiis saepe dolores architecto nesciunt tempore nihil, quos voluptates tenetur cumque natus voluptatum? Dicta vitae repellendus cupiditate eum iste earum velit ex cum','99.9%','de estatística. Mais uma estatística qualquer.','Os nossos alunos'),
	 (108,'Teachers','Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur non eos id neque amet. Vero quaerat soluta ratione facere maxime, odio nemo magnam perspiciatis sunt eum atque! Earum adipisci suscipit asperiores, placeat qui cumque. Nostrum corrupti veritatis at veniam id odio, nisi incidunt nobis vitae laudantium laboriosam officiis saepe dolores architecto nesciunt tempore nihil, quos voluptates tenetur cumque natus voluptatum? Dicta vitae repellendus cupiditate eum iste earum velit ex cum','70%','dos professores têm experiência no mercado de trabalho.','Os professores'),
	 (109,'Courses','Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur non eos id neque amet. Vero quaerat soluta ratione facere maxime, odio nemo magnam perspiciatis sunt eum atque! Earum adipisci suscipit asperiores, placeat qui cumque. Nostrum corrupti veritatis at veniam id odio, nisi incidunt nobis vitae laudantium laboriosam officiis saepe dolores architecto nesciunt tempore nihil, quos voluptates tenetur cumque natus','6','cursos no nosso departamento. Qual é o teu?','E agora?');

INSERT INTO deisi_backend.student (id,description,grad_year,img_src,name) VALUES
 	 (110,'A Lusófona tem um ensino muito bom e professores que se preocupam que os alunos aprendam e que tenham uma boa carreira. Uma experiência que vou levar comigo para sempre no meu percurso profissional.',2022,'https://ik.imagekit.io/smm2b6sqe/students_photos/bruno-bacelar_F7tDk81KP.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1650798806492','Bruno Bacelar'),
 	 (111,'A minha experiência na Lusófona foi algo soberbo, em todos os sentidos. É o que se costuma dizer de "life changing". Não é fácil a adaptação de uma pessoa a ingressar numa licenciatura aos 35 anos, mas foi o melhor passo que poderia ter dado!',2014,'https://ik.imagekit.io/smm2b6sqe/students_photos/hugo-serras_FAORaqqff.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1650798806875','Hugo Serras'),
 	 (112,'Não subestimo os números num certificado. Mas, mais importante que a "beleza" dos números é a historia por de trás deles, Isso sim determinará o tipo de profissional que nascerá de ti. Eu escrevi as minhas melhores histórias na Lusófona.',2009,'https://ik.imagekit.io/smm2b6sqe/students_photos/caldina-pires_ux9z0Gpxt.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1650798806599','Caldina Pires'),
 	 (113,'Entrei sem saber uma única linha de código e saí com a sensação que podia fazer a diferença no mundo empresarial.',2014,'https://ik.imagekit.io/smm2b6sqe/students_photos/tiago_pinto_DN0JlHLia.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1650798806626','Tiago Pinto'),
 	 (114,'A ULHT me permitiu dar os meus primeiros passos para realizar os meus sonhos académicos e profissional. Professores com uma elevada experiência profissional e grau académico me permitiu a construir um perfil de pensamento critico para resolução de problemas.',2022,'https://ik.imagekit.io/smm2b6sqe/students_photos/clid-robalo_Fv5AULtbv.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1650798807004','Clid Robalo'),
 	 (115,'O meu tempo na Lusófona foi de muito trabalho e muita aprendizagem onde felizmente contactei com excelentes professores e excelentes colegas que me proporcionaram a possibilidade de estar mais preparado para o papel que desempenho hoje em dia no meu trabalho.',2014,'https://ik.imagekit.io/smm2b6sqe/students_photos/fransisco_santos_rbgIDHTIp?ik-sdk-version=javascript-1.4.3&updatedAt=1650801268167','Francisco Santos'),
 	 (116,'Desafio e superação.',2016,'https://ik.imagekit.io/smm2b6sqe/students_photos/ad%C3%A3o_pedro_0hhrjv8N1?ik-sdk-version=javascript-1.4.3&updatedAt=1650801140629','Adão Pedro');

INSERT INTO deisi_backend.teacher (id,age,name,description,img_src) VALUES
	 (38,30,'Pedro Alves','Professor 1','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475'),
	 (39,18,'Miguel Tavares','Professor 2','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475'),
	 (40,19,'Rui Ribeiro','Professor 3','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475'),
	 (41,22,'Sérgio Nunes','Professor 4','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475'),
	 (42,21,'Pedro Perdigão','Professor 5','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475'),
	 (44,25,'Lucio Studer','Professor 6','https://ik.imagekit.io/smm2b6sqe/zuck_phDBAvN_b.png?ik-sdk-version=javascript-1.4.3&updatedAt=1649766802475');
